# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19fB_n7rC-Glyp6LhUKpxyyPF4-6U86WB
"""

# =========================
# IMPORT LIBRARIES
# =========================
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from google.colab import files
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

# =========================
# UPLOAD DATASET
# =========================
uploaded = files.upload()
filename = list(uploaded.keys())[0]

# =========================
# LOAD DATA
# =========================
df = pd.read_csv(filename)

print("Dataset Shape:", df.shape)
display(df.head())

# =========================
# CLEAN DATA
# =========================
num = df.select_dtypes(include=np.number).columns
df[num] = df[num].fillna(df[num].median())

cat = df.select_dtypes(include="object").columns
df[cat] = df[cat].fillna("Unknown")

df = df.drop_duplicates()

# =========================
# ENCODE CATEGORICAL
# =========================
le = LabelEncoder()
for col in cat:
    df[col] = le.fit_transform(df[col])

# =========================
# HISTOGRAMS (CLEAN)
# =========================
df.hist(figsize=(25,22), bins=20, edgecolor="black")
plt.suptitle("Feature Distributions", fontsize=22)
plt.tight_layout(rect=[0,0,1,0.97])
plt.show()

# =========================
# CORRELATION HEATMAP (CLEAN)
# =========================
plt.figure(figsize=(22,18))

corr = df.corr()

sns.heatmap(
    corr,
    cmap="coolwarm",
    center=0,
    linewidths=0.3,
    cbar_kws={"shrink": .8}
)

plt.title("Correlation Matrix", fontsize=22)
plt.xticks(fontsize=8, rotation=90)
plt.yticks(fontsize=8)
plt.tight_layout()
plt.show()

# =========================
# TARGET VARIABLE
# =========================
target = "Howlikelyisitthatyouwouldrecommendthisapptoafriendorcolleague"

X = df.drop(columns=[target])
y = df[target]

# =========================
# TRAIN TEST SPLIT
# =========================
X_train,X_test,y_train,y_test = train_test_split(
    X,y,test_size=0.2,random_state=42
)

# =========================
# MODEL TRAINING
# =========================
model = RandomForestClassifier()
model.fit(X_train,y_train)

pred = model.predict(X_test)

print("\nModel Accuracy:", accuracy_score(y_test,pred))

# =========================
# FEATURE IMPORTANCE
# =========================
importance = pd.Series(model.feature_importances_, index=X.columns)

top = importance.sort_values(ascending=False).head(12)

plt.figure(figsize=(10,7))
top.sort_values().plot(
    kind="barh",
    color="teal",
    edgecolor="black"
)

plt.title("Top Factors Influencing Recommendation", fontsize=18)
plt.xlabel("Importance Score")
plt.grid(axis="x", linestyle="--", alpha=0.6)

plt.tight_layout()
plt.show()

print("\nTop Important Features:")
print(top)